spring: 
   redis:
     lettuce:
       pool:
         max-active: 6
         max-idle: 3
         max-wait: 100ms
         min-idle: 1
     host: localhost
     port: 6379
     password:
#    cluster:
#      nodes:
#        - ip:port
#        - ip:port
#        - ip:port

# jedis 和 lettuce 的区别:
# 1. SpringBoot2.0 之后默认采用 lettuce 作为 redis 的连接
# 2. jedis 是直连 redis server 模式,在多线程环境下是线程不安全的,可以使用 jedis pool 来解决
# 3. lettuce 是基于 Netty 的模式,连接实例可以在多个线程间并发访问,方法调用是异步的也是线程安全的
# 4. 在高并发情况下,jedis 可以通过调整连接池的数量来增加吞吐量,但是不可避免连接超时和长时间等待;
#     jedis 的最大连接数和最大空闲和最小空闲设置为同一个值可以减少上下文切换,提升效率;
# 5. lettuce 的连接池大小不宜设置过大,最好的是 CPU 的核数+1
