
spring:
  freemarker:
    # 设置是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性。
    allow-request-override: false
    # 设置是否允许HttpSession属性覆盖(隐藏)控制器生成的同名模型属性。
    #    allow-session-override: false
    # 关闭缓存, 热启动 方便本地调试(build 后刷新界面即可), 上生产改为 true
    cache: false
    #检查模板位置是否存在。
    check-template-location: true
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: utf-8
    # 为这种技术启用MVC视图解决方案。
    #    enabled: true
    # 设置是否应该在与模板合并之前将所有请求属性添加到模型中。
    expose-request-attributes: false
    # 设置是否在与模板合并之前将所有 HttpSession 属性添加到模型中。
    expose-session-attributes: false
    # 设置是否公开 RequestContext 供 Spring 宏库使用, 名称为"SpringMacroRequestContext"。
    expose-spring-macro-helpers: false
    # 更喜欢文件系统访问模板加载, 文件系统访问允许对模板更改进行热检测。
    prefer-file-system-access: false
    # 设置模板前缀名, 用于在构建 URL 时查看名称
    #    prefix:
    # 设置模板后缀名, 用于在构建 URL 时查看名称
    request-context-attribute: request
    # 众所周知的 FreeMarker 密钥将传递给 FreeMarker 的配置。
    settings:
      number_format: 0.##
    # 所有视图的 RequestContext 属性的名称。
    suffix: .html
    # 设置文件路径, 以逗号分隔的模板路径列表。
    template-loader-path: classpath:/templates/
    # 可以解析的视图名称的白列表。
    #    view-names:
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**