spring:
  # springboot 内置的 Tomcat 默认上传文件大小为 1M, 低版本 springboot 将 servlet 改为 http
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 总文件大小(允许存储文件的文件夹大小)
      max-request-size: 100MB

fdfs:
  so-timeout: 1501
  connect-timeout: 601
#  thumb-image:             #缩略图生成参数
#    width: 150
#    height: 150
  tracker-list:            #TrackerList参数,支持多个
#    - 139.224.130.26:22122
    - 11.11.237.205:22122
#  web-server-url: 139.224.130.26:8093/
  web-server-url: 11.11.237.205:8888/
  pool:
    # 连接池最大数量
    max-total: 200
    # 单个tracker最大连接数
    max-total-per-key: 50
    # 连接耗尽最大等待时间(毫秒)
    max-wait-millis: 5000

common:
  file:
    native:
      fileUploadTempDir: /Users/liuzhichao/fileupload
      fileUploadDir: /Users/liuzhichao/fileupload
      upload-path: /Users/liuzhichao/fileupload
